In [20]:
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time,requests
from selenium.common.exceptions import NoSuchElementException

In [21]:
driver = webdriver.Chrome(r'C:\New folder\webdriver.exe')

In [22]:
#1
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [32]:
Rank = []
Name = []
Artist = []
Upload_date = []
Views = []

In [34]:
tag1 = driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]')
for i in tag1:
    Rank.append(i.text.split('\n')[2:32])

In [73]:
Rank[0][0].split('.')[0]

'1'

In [52]:
#2
driver = webdriver.Chrome(r'C:\New folder\webdriver.exe')
driver.get('http://www.bcci.tv/')

In [44]:
search1 = driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a')
search1.click()

In [49]:
Match_title = []
Series = []
Place = []
Date = []
Time = []

In [50]:
tag1 = driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')
for i in tag1:
    Match_title.append(i.text)

tag2 = driver.find_elements(By.XPATH,'//span[@class="ng-binding"]')
for i in tag2:
    Series.append(i.text)

tag3 = driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]')
for i in tag3:
    Place.append(i.text)

tag4 = driver.find_elements(By.XPATH,'//div[@class="match-card-left match-schedule"]')
for i in tag4:
    Date.append(i.text)

tag5 = driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]')
for i in tag5:
    Time.append(i.text)

In [51]:
print(len(Match_title),len(Series),len(Place),len(Date),len(Time))

8 8 8 8 8

In [52]:
df = pd.DataFrame({'Match title':Match_title,'Series':Series,'Place':Place,'Date':Date,'Time':Time})
df

,Match title,Series,Place,Date,Time
0,ICC WOMENS T20 WORLD CUP 2023,ICC WOMENS T20 WORLD CUP 2023,"Newlands,",15 FEB 2023,6:30 PM IST
1,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Arun Jaitley Stadium,",17 FEB 2023,9:30 AM IST
2,ICC WOMENS T20 WORLD CUP 2023,ICC WOMENS T20 WORLD CUP 2023,"St George's Park,",18 FEB 2023,6:30 PM IST
3,ICC WOMENS T20 WORLD CUP 2023,ICC WOMENS T20 WORLD CUP 2023,"St George's Park,",20 FEB 2023,6:30 PM IST
4,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Himachal Pradesh Cricket Association Stadium,",1 MAR 2023,9:30 AM IST
5,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Narendra Modi Stadium,",9 MAR 2023,9:30 AM IST
6,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,"Wankhede Stadium,",17 MAR 2023,1:30 PM IST
7,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,AUSTRALIA TOUR OF INDIA ODI SERIES 2022-23,"Dr YS Rajasekhara Reddy ACA-VDCA Cricket Stadium,",19 MAR 2023,1:30 PM IST

In [43]:
#3
driver = webdriver.Chrome(r'C:\New folder\webdriver.exe')
driver.get('http://statisticstimes.com/')

In [44]:
search1 = driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/a[3]')
search1.click()

In [46]:
search2 = driver.find_element(By.CLASS_NAME,'dropbtn')
search2.click()

In [47]:
search3 = driver.find_element(By.XPATH,'/html/body/div[2]/div[1]/div[2]/div[1]/div/a[2]')
search3.click()

In [48]:
search4 = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[1]/div[1]/p[2]/a')
search4.click()

In [49]:
search5 = driver.find_element(By.XPATH,'/html/body/div[3]/div[2]/div[2]/div[5]/ul/li[6]/a')
search5.click()

In [50]:
search6 = driver.find_element(By.XPATH,'/html/body/div[2]/div[2]/div[2]/ul/li[3]/a')
search6.click()

In [55]:
Rank = []
State = []
GSDP_18_19 = []
GSDP_19_20 = []
Share_18_19 = []
GDP_in_billion = []

In [56]:
tag1 = driver.find_elements(By.XPATH,'//td[@class="data1"]')
for i in tag1[0:33]:
    Rank.append(i.text)

tag2 = driver.find_elements(By.XPATH,'//td[@class="name"]')
for i in tag2[0:33]:
    State.append(i.text)

tag3 = driver.find_elements(By.XPATH,'//td[@class="data sorting_1"]')
for i in tag3[0:33]:
    GSDP_18_19.append(i.text)

tag4 = driver.find_elements(By.XPATH,'//td[@class="data"]')
for i in tag4[0:33]:
    GSDP_19_20.append(i.text)

tag5 = driver.find_elements(By.XPATH,'//td[@class="data"]')
for i in tag5[0:33]:
    Share_18_19.append(i.text)

tag6 = driver.find_elements(By.XPATH,'//td[@class="data"]')
for i in tag6[0:33]:
    GDP_in_billion.append(i.text)

In [57]:
print(len(Rank),len(State),len(GSDP_18_19),len(GSDP_19_20),len(Share_18_19),len(GDP_in_billion))

33 33 33 33 33 33

In [58]:
df = pd.DataFrame({'Rank':Rank,'State':State,'GSDP OF 2018 2019':GSDP_18_19,'GSDP OF 2019 2020':GSDP_19_20,
                   'Shares of 2018 2019':Share_18_19,'GDP in Billion':GDP_in_billion})
df

,Rank,State,GSDP OF 2018 2019,GSDP OF 2019 2020,Shares of 2018 2019,GDP in Billion
0,1,Mizoram,12.56,14.07,14.07,14.07
1,2,Tripura,9.94,11.63,11.63,11.63
2,3,Gujarat,9.83,18.91,18.91,18.91
3,4,Karnataka,8.79,14.97,14.97,14.97
4,5,Haryana,8.64,17.56,17.56,17.56
5,6,Delhi,8.04,9.79,9.79,9.79
6,7,Telangana,7.96,11.69,11.69,11.69
7,8,Sikkim,7.72,12.32,12.32,12.32
8,9,Uttarakhand,7.66,14.02,14.02,14.02
9,10,Chandigarh,7.54,14.66,14.66,14.66
10,11,Madhya Pradesh,7.50,-,-,-
11,12,Andhra Pradesh,7.36,9.19,9.19,9.19
12,13,Assam,7.34,-,-,-
13,14,Odisha,7.32,13.08,13.08,13.08
14,15,Himachal Pradesh,7.14,13.61,13.61,13.61
15,16,Tamil Nadu,7.12,5.95,5.95,5.95
16,17,Maharashtra,6.88,6.67,6.67,6.67
17,18,Rajasthan,6.54,9.30,9.30,9.30
18,19,Uttar Pradesh,6.51,11.68,11.68,11.68
19,20,Kerala,6.34,13.77,13.77,13.77
20,21,Bihar,6.18,7.75,7.75,7.75
21,22,Arunachal Pradesh,6.17,7.49,7.49,7.49
22,23,Jharkhand,6.04,13.27,13.27,13.27
23,24,Manipur,5.96,13.02,13.02,13.02
24,25,Punjab,5.88,13.79,13.79,13.79
25,26,Chhattisgarh,5.61,7.42,7.42,7.42
26,27,Jammu & Kashmir,5.51,7.71,7.71,7.71
27,28,Goa,5.48,10.48,10.48,10.48
28,29,Nagaland,5.46,12.82,12.82,12.82
29,30,West Bengal,5.16,12.31,12.31,12.31
30,31,Puducherry,4.69,8.23,8.23,8.23
31,32,Meghalaya,3.17,9.53,9.53,9.53
32,33,Andaman & Nicobar Islands,-,12.61,12.61,12.61

In [7]:
#4
driver = webdriver.Chrome(r'C:\New folder\webdriver.exe')
driver.get('https://github.com/')

In [8]:
search1 = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button')
search1.click()

In [9]:
search2 = driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a')
search2.click()

In [33]:
Repository_title = []
Repository_description = []
Contributors_count = []
Language_used = []

In [34]:
try:
    tag1 = driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]')
    for i in tag1:
        Repository_title.append(i.text)
except NoSuchElementException as e:
    Repository_title.append('-')
    
try:
    tag2 = driver.find_elements(By.XPATH,'//p[@class="col-9 color-fg-muted my-1 pr-4"]')
    for i in tag2:
        Repository_description.append(i.text)
except NoSuchElementException as e:
    Repository_description.append('-')
    
try:
    tag3 = driver.find_elements(By.XPATH,'//a[@class="Link--muted d-inline-block mr-3"][2]')
    for i in tag3:
        Contributors_count.append(i.text)
except NoSuchElementException as e:
    Contributors_count.append('-')
    
try:
    tag4 = driver.find_elements(By.XPATH,'//span[@class="d-inline-block ml-0 mr-3"]')
    for i in tag4:
        Language_used.append(i.text)
except NoSuchElementException as e:
    Language_used.append('-')

In [35]:
print(len(Repository_title),len(Repository_description),len(Contributors_count),len(Language_used))

25 23 25 21

In [36]:
df = pd.DataFrame({'Repository title':Repository_title[0:21],'Repository description':Repository_description[0:21],
                   'Contributors count':Contributors_count[0:21],'Language used':Language_used[0:21]})
df

,Repository title,Repository description,Contributors count,Language used
0,zhayujie / chatgpt-on-wechat,使用ChatGPT搭建微信聊天机器人，基于OpenAI API和itchat实现。Wecha...,351,Python
1,PlexPt / awesome-chatgpt-prompts-zh,ChatGPT 中文调教指南。各种场景使用指南。学习怎么让它听你的话。,"2,149",Rust
2,rustdesk / rustdesk,Open source virtual / remote desktop infrastru...,"3,357",HTML
3,f / awesome-chatgpt-prompts,This repo includes ChatGPT prompt curation to ...,"2,383",Go
4,sashabaranov / go-gpt3,OpenAI GPT-3 and DALL·E API wrapper for Go,89,Python
5,openai / gpt-2,"Code for the paper ""Language Models are Unsupe...","4,218",TypeScript
6,eliaszon / Programmers-Overseas-Job-Interview-...,🏂🏻 程序员海外工作/英文面试手册,115,Shell
7,AutumnWhj / ChatGPT-wechat-bot,ChatGPT for wechat https://github.com/AutumnWh...,525,TypeScript
8,cisagov / ESXiArgs-Recover,A tool to recover from ESXiArgs ransomware,26,Rust
9,fuergaosi233 / wechat-chatgpt,Use ChatGPT On Wechat via wechaty,"1,868",Jupyter Notebook
10,obi1kenobi / trustfall,If GraphQL were more like SQL: a query languag...,36,Python
11,c4s73r / NetworkNightmare,Network Pentesting Mindmap by Caster,21,HTML
12,openai / openai-cookbook,Examples and guides for using the OpenAI API,"1,375",Dart
13,YuxinWenRick / hard-prompts-made-easy,eski surum,16,Rust
14,acikkaynak / deprem-io-frontend,"Bu uygulama, ihtiyaç sahibi depremzedelerin ha...",17,Rust
15,acikkaynak / yardim-agi-flutter,"🔮 ChatGPT Desktop Application (Mac, Windows an...",63,Java
16,lencx / ChatGPT,👁‍🗨 Rare and exotic sats,"1,051",Shell
17,casey / ord,ChatGPT Java SDK. Lightweight package for inte...,104,Python
18,PlexPt / chatgpt-java,Cloud Flare scanner,107,Python
19,MortezaBashsiz / CFScanner,afetharita.com backend projesi,51,TypeScript
20,acikkaynak / deprem-yardim-backend,RWKV is a RNN with transformer-level LLM perfo...,90,TypeScript

In [2]:
#5
driver = webdriver.Chrome(r'C:\New folder\webdriver.exe')
driver.get('https://www.billboard.com/')

In [3]:
search1 = driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a')
search1.click()

In [4]:
search2 = driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a')
search2.click()

In [17]:
Song_name = []
Artist_name = []
Last_week_rank = []
Peak_rank = []
Weeks_on_chart = []

In [18]:
tag1 = driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]')
for i in tag1:
    Song_name.append(i.text.split('\n')[1])
    Artist_name.append(i.text.split('\n')[2])
    Last_week_rank.append(i.text.split('\n')[3])
    Peak_rank.append(i.text.split('\n')[4])
    Weeks_on_chart.append(i.text.split('\n')[5])

In [27]:
print(len(Song_name),len(Artist_name),len(Last_week_rank),len(Peak_rank),len(Weeks_on_chart))

100 100 100 100 100

In [29]:
df = pd.DataFrame({'Song_name':Song_name,'Artist_name':Artist_name,'Last_week_rank':Last_week_rank,'Peak_rank':Peak_rank,'Weeks_on_chart':Weeks_on_chart})
df

,Song_name,Artist_name,Last_week_rank,Peak_rank,Weeks_on_chart
0,Flowers,Miley Cyrus,1,1,3
1,Kill Bill,SZA,2,2,8
2,Creepin',"Metro Boomin, The Weeknd & 21 Savage",4,3,9
3,Anti-Hero,Taylor Swift,3,1,15
4,Unholy,Sam Smith & Kim Petras,5,1,19
...,...,...,...,...,...
95,NEW,Hey Mor,Ozuna Featuring Feid,-,96
96,Gato de Noche,Nengo Flow & Bad Bunny,85,60,6
97,Heart To Heart,Mac DeMarco,83,83,3
98,NEW,Never Gonna Not Dance Again,P!nk,-,99
99,NEW,Dancin' In The Country,Tyler Hubbard,-,100

In [7]:
#6
driver = webdriver.Chrome(r'C:\New folder\webdriver.exe')
driver.get('https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare')

In [23]:
Book_name = []
Author_name = []
Volumes_sold = []
Publisher = []
Genre = []

In [29]:
tag1 = driver.find_elements(By.XPATH,'//td[@class="left"]')
for i in tag1:
    Book_name.append(i.text.split()[0])

In [30]:
Book_name

[['1'],
 ['Da', 'Vinci', 'Code,The'],
 ['Brown,', 'Dan'],
 ['5,094,805'],
 ['Transworld'],
 ['2'],
 ['Harry', 'Potter', 'and', 'the', 'Deathly', 'Hallows'],
 ['Rowling,', 'J.K.'],
 ['4,475,152'],
 ['Bloomsbury'],
 ['3'],
 ['Harry', 'Potter', 'and', 'the', "Philosopher's", 'Stone'],
 ['Rowling,', 'J.K.'],
 ['4,200,654'],
 ['Bloomsbury'],
 ['4'],
 ['Harry', 'Potter', 'and', 'the', 'Order', 'of', 'the', 'Phoenix'],
 ['Rowling,', 'J.K.'],
 ['4,179,479'],
 ['Bloomsbury'],
 ['5'],
 ['Fifty', 'Shades', 'of', 'Grey'],
 ['James,', 'E.', 'L.'],
 ['3,758,936'],
 ['Random', 'House'],
 ['6'],
 ['Harry', 'Potter', 'and', 'the', 'Goblet', 'of', 'Fire'],
 ['Rowling,', 'J.K.'],
 ['3,583,215'],
 ['Bloomsbury'],
 ['7'],
 ['Harry', 'Potter', 'and', 'the', 'Chamber', 'of', 'Secrets'],
 ['Rowling,', 'J.K.'],
 ['3,484,047'],
 ['Bloomsbury'],
 ['8'],
 ['Harry', 'Potter', 'and', 'the', 'Prisoner', 'of', 'Azkaban'],
 ['Rowling,', 'J.K.'],
 ['3,377,906'],
 ['Bloomsbury'],
 ['9'],
 ['Angels', 'and', 'Demons'],
 ['Brown,', 'Dan'],
 ['3,193,946'],
 ['Transworld'],
 ['10'],
 ['Harry',
  'Potter',
  'and',
  'the',
  'Half-blood',
  "Prince:Children's",
  'Edition'],
 ['Rowling,', 'J.K.'],
 ['2,950,264'],
 ['Bloomsbury'],
 ['11'],
 ['Fifty', 'Shades', 'Darker'],
 ['James,', 'E.', 'L.'],
 ['2,479,784'],
 ['Random', 'House'],
 ['12'],
 ['Twilight'],
 ['Meyer,', 'Stephenie'],
 ['2,315,405'],
 ['Little,', 'Brown', 'Book'],
 ['13'],
 ['Girl', 'with', 'the', 'Dragon', 'Tattoo,The:Millennium', 'Trilogy'],
 ['Larsson,', 'Stieg'],
 ['2,233,570'],
 ['Quercus'],
 ['14'],
 ['Fifty', 'Shades', 'Freed'],
 ['James,', 'E.', 'L.'],
 ['2,193,928'],
 ['Random', 'House'],
 ['15'],
 ['Lost', 'Symbol,The'],
 ['Brown,', 'Dan'],
 ['2,183,031'],
 ['Transworld'],
 ['16'],
 ['New', 'Moon'],
 ['Meyer,', 'Stephenie'],
 ['2,152,737'],
 ['Little,', 'Brown', 'Book'],
 ['17'],
 ['Deception', 'Point'],
 ['Brown,', 'Dan'],
 ['2,062,145'],
 ['Transworld'],
 ['18'],
 ['Eclipse'],
 ['Meyer,', 'Stephenie'],
 ['2,052,876'],
 ['Little,', 'Brown', 'Book'],
 ['19'],
 ['Lovely', 'Bones,The'],
 ['Sebold,', 'Alice'],
 ['2,005,598'],
 ['Pan', 'Macmillan'],
 ['20'],
 ['Curious', 'Incident', 'of', 'the', 'Dog', 'in', 'the', 'Night-time,The'],
 ['Haddon,', 'Mark'],
 ['1,979,552'],
 ['Random', 'House'],
 ['21'],
 ['Digital', 'Fortress'],
 ['Brown,', 'Dan'],
 ['1,928,900'],
 ['Transworld'],
 ['22'],
 ['Short', 'History', 'of', 'Nearly', 'Everything,A'],
 ['Bryson,', 'Bill'],
 ['1,852,919'],
 ['Transworld'],
 ['23'],
 ['Girl', 'Who', 'Played', 'with', 'Fire,The:Millennium', 'Trilogy'],
 ['Larsson,', 'Stieg'],
 ['1,814,784'],
 ['Quercus'],
 ['24'],
 ['Breaking', 'Dawn'],
 ['Meyer,', 'Stephenie'],
 ['1,787,118'],
 ['Little,', 'Brown', 'Book'],
 ['25'],
 ['Very', 'Hungry', 'Caterpillar,The:The', 'Very', 'Hungry', 'Caterpillar'],
 ['Carle,', 'Eric'],
 ['1,783,535'],
 ['Penguin'],
 ['26'],
 ['Gruffalo,The'],
 ['Donaldson,', 'Julia'],
 ['1,781,269'],
 ['Pan', 'Macmillan'],
 ['27'],
 ["Jamie's", '30-Minute', 'Meals'],
 ['Oliver,', 'Jamie'],
 ['1,743,266'],
 ['Penguin'],
 ['28'],
 ['Kite', 'Runner,The'],
 ['Hosseini,', 'Khaled'],
 ['1,629,119'],
 ['Bloomsbury'],
 ['29'],
 ['One', 'Day'],
 ['Nicholls,', 'David'],
 ['1,616,068'],
 ['Hodder', '&', 'Stoughton'],
 ['30'],
 ['Thousand', 'Splendid', 'Suns,A'],
 ['Hosseini,', 'Khaled'],
 ['1,583,992'],
 ['Bloomsbury'],
 ['31'],
 ['Girl',
  'Who',
  'Kicked',
  'the',
  "Hornets'",
  'Nest,The:Millennium',
  'Trilogy'],
 ['Larsson,', 'Stieg'],
 ['1,555,135'],
 ['Quercus'],
 ['32'],
 ['Time', "Traveler's", 'Wife,The'],
 ['Niffenegger,', 'Audrey'],
 ['1,546,886'],
 ['Random', 'House'],
 ['33'],
 ['Atonement'],
 ['McEwan,', 'Ian'],
 ['1,539,428'],
 ['Random', 'House'],
 ['34'],
 ['Bridget', "Jones's", 'Diary:A', 'Novel'],
 ['Fielding,', 'Helen'],
 ['1,508,205'],
 ['Pan', 'Macmillan'],
 ['35'],
 ['World', 'According', 'to', 'Clarkson,The'],
 ['Clarkson,', 'Jeremy'],
 ['1,489,403'],
 ['Penguin'],
 ['36'],
 ['Captain', "Corelli's", 'Mandolin'],
 ['Bernieres,', 'Louis', 'de'],
 ['1,352,318'],
 ['Random', 'House'],
 ['37'],
 ['Sound', 'of', 'Laughter,The'],
 ['Kay,', 'Peter'],
 ['1,310,207'],
 ['Random', 'House'],
 ['38'],
 ['Life', 'of', 'Pi'],
 ['Martel,', 'Yann'],
 ['1,310,176'],
 ['Canongate'],
 ['39'],
 ['Billy', 'Connolly'],
 ['Stephenson,', 'Pamela'],
 ['1,231,957'],
 ['HarperCollins'],
 ['40'],
 ['Child', 'Called', 'It,A'],
 ['Pelzer,', 'Dave'],
 ['1,217,712'],
 ['Orion'],
 ['41'],
 ["Gruffalo's", 'Child,The'],
 ['Donaldson,', 'Julia'],
 ['1,208,711'],
 ['Pan', 'Macmillan'],
 ['42'],
 ["Angela's", 'Ashes:A', 'Memoir', 'of', 'a', 'Childhood'],
 ['McCourt,', 'Frank'],
 ['1,204,058'],
 ['HarperCollins'],
 ['43'],
 ['Birdsong'],
 ['Faulks,', 'Sebastian'],
 ['1,184,967'],
 ['Random', 'House'],
 ['44'],
 ['Northern', 'Lights:His', 'Dark', 'Materials', 'S.'],
 ['Pullman,', 'Philip'],
 ['1,181,503'],
 ['Scholastic', 'Ltd.'],
 ['45'],
 ['Labyrinth'],
 ['Mosse,', 'Kate'],
 ['1,181,093'],
 ['Orion'],
 ['46'],
 ['Harry', 'Potter', 'and', 'the', 'Half-blood', 'Prince'],
 ['Rowling,', 'J.K.'],
 ['1,153,181'],
 ['Bloomsbury'],
 ['47'],
 ['Help,The'],
 ['Stockett,', 'Kathryn'],
 ['1,132,336'],
 ['Penguin'],
 ['48'],
 ['Man', 'and', 'Boy'],
 ['Parsons,', 'Tony'],
 ['1,130,802'],
 ['HarperCollins'],
 ['49'],
 ['Memoirs', 'of', 'a', 'Geisha'],
 ['Golden,', 'Arthur'],
 ['1,126,337'],
 ['Random', 'House'],
 ['50'],
 ['No.1',
  "Ladies'",
  'Detective',
  'Agency,The:No.1',
  "Ladies'",
  'Detective',
  'Agency',
  'S.'],
 ['McCall', 'Smith,', 'Alexander'],
 ['1,115,549'],
 ['Little,', 'Brown', 'Book'],
 ['51'],
 ['Island,The'],
 ['Hislop,', 'Victoria'],
 ['1,108,328'],
 ['Headline'],
 ['52'],
 ['PS,', 'I', 'Love', 'You'],
 ['Ahern,', 'Cecelia'],
 ['1,107,379'],
 ['HarperCollins'],
 ['53'],
 ['You',
  'are',
  'What',
  'You',
  'Eat:The',
  'Plan',
  'That',
  'Will',
  'Change',
  'Your',
  'Life'],
 ['McKeith,', 'Gillian'],
 ['1,104,403'],
 ['Penguin'],
 ['54'],
 ['Shadow', 'of', 'the', 'Wind,The'],
 ['Zafon,', 'Carlos', 'Ruiz'],
 ['1,092,349'],
 ['Orion'],
 ['55'],
 ['Tales', 'of', 'Beedle', 'the', 'Bard,The'],
 ['Rowling,', 'J.K.'],
 ['1,090,847'],
 ['Bloomsbury'],
 ['56'],
 ['Broker,The'],
 ['Grisham,', 'John'],
 ['1,087,262'],
 ['Random', 'House'],
 ['57'],
 ['Dr.',
  "Atkins'",
  'New',
  'Diet',
  'Revolution:The',
  'No-hunger,',
  'Luxurious',
  'Weight',
  'Loss',
  'P'],
 ['Atkins,', 'Robert', 'C.'],
 ['1,054,196'],
 ['Random', 'House'],
 ['58'],
 ['Subtle', 'Knife,The:His', 'Dark', 'Materials', 'S.'],
 ['Pullman,', 'Philip'],
 ['1,037,160'],
 ['Scholastic', 'Ltd.'],
 ['59'],
 ['Eats,',
  'Shoots',
  'and',
  'Leaves:The',
  'Zero',
  'Tolerance',
  'Approach',
  'to',
  'Punctuation'],
 ['Truss,', 'Lynne'],
 ['1,023,688'],
 ['Profile', 'Books', 'Group'],
 ['60'],
 ["Delia's", 'How', 'to', 'Cook:(Bk.1)'],
 ['Smith,', 'Delia'],
 ['1,015,956'],
 ['Random', 'House'],
 ['61'],
 ['Chocolat'],
 ['Harris,', 'Joanne'],
 ['1,009,873'],
 ['Transworld'],
 ['62'],
 ['Boy', 'in', 'the', 'Striped', 'Pyjamas,The'],
 ['Boyne,', 'John'],
 ['1,004,414'],
 ['Random', 'House', 'Childrens', 'Books', 'G'],
 ['63'],
 ['My', "Sister's", 'Keeper'],
 ['Picoult,', 'Jodi'],
 ['1,003,780'],
 ['Hodder', '&', 'Stoughton'],
 ['64'],
 ['Amber', 'Spyglass,The:His', 'Dark', 'Materials', 'S.'],
 ['Pullman,', 'Philip'],
 ['1,002,314'],
 ['Scholastic', 'Ltd.'],
 ['65'],
 ['To', 'Kill', 'a', 'Mockingbird'],
 ['Lee,', 'Harper'],
 ['998,213'],
 ['Random', 'House'],
 ['66'],
 ['Men',
  'are',
  'from',
  'Mars,',
  'Women',
  'are',
  'from',
  'Venus:A',
  'Practical',
  'Guide',
  'for',
  'Improvin'],
 ['Gray,', 'John'],
 ['992,846'],
 ['HarperCollins'],
 ['67'],
 ['Dear', 'Fatty'],
 ['French,', 'Dawn'],
 ['986,753'],
 ['Random', 'House'],
 ['68'],
 ['Short', 'History', 'of', 'Tractors', 'in', 'Ukrainian,A'],
 ['Lewycka,', 'Marina'],
 ['986,115'],
 ['Penguin'],
 ['69'],
 ['Hannibal'],
 ['Harris,', 'Thomas'],
 ['970,509'],
 ['Random', 'House'],
 ['70'],
 ['Lord', 'of', 'the', 'Rings,The'],
 ['Tolkien,', 'J.', 'R.', 'R.'],
 ['967,466'],
 ['HarperCollins'],
 ['71'],
 ['Stupid',
  'White',
  'Men:...and',
  'Other',
  'Sorry',
  'Excuses',
  'for',
  'the',
  'State',
  'of',
  'the',
  'Natio'],
 ['Moore,', 'Michael'],
 ['963,353'],
 ['Penguin'],
 ['72'],
 ['Interpretation', 'of', 'Murder,The'],
 ['Rubenfeld,', 'Jed'],
 ['962,515'],
 ['Headline'],
 ['73'],
 ['Sharon', 'Osbourne', 'Extreme:My', 'Autobiography'],
 ['Osbourne,', 'Sharon'],
 ['959,496'],
 ['Little,', 'Brown', 'Book'],
 ['74'],
 ['Alchemist,The:A', 'Fable', 'About', 'Following', 'Your', 'Dream'],
 ['Coelho,', 'Paulo'],
 ['956,114'],
 ['HarperCollins'],
 ['75'],
 ['At', 'My', "Mother's", 'Knee', '...:and', 'Other', 'Low', 'Joints'],
 ["O'Grady,", 'Paul'],
 ['945,640'],
 ['Transworld'],
 ['76'],
 ['Notes', 'from', 'a', 'Small', 'Island'],
 ['Bryson,', 'Bill'],
 ['931,312'],
 ['Transworld'],
 ['77'],
 ['Return', 'of', 'the', 'Naked', 'Chef,The'],
 ['Oliver,', 'Jamie'],
 ['925,425'],
 ['Penguin'],
 ['78'],
 ['Bridget', 'Jones:', 'The', 'Edge', 'of', 'Reason'],
 ['Fielding,', 'Helen'],
 ['924,695'],
 ['Pan', 'Macmillan'],
 ['79'],
 ["Jamie's", 'Italy'],
 ['Oliver,', 'Jamie'],
 ['906,968'],
 ['Penguin'],
 ['80'],
 ['I', 'Can', 'Make', 'You', 'Thin'],
 ['McKenna,', 'Paul'],
 ['905,086'],
 ['Transworld'],
 ['81'],
 ['Down', 'Under'],
 ['Bryson,', 'Bill'],
 ['890,847'],
 ['Transworld'],
 ['82'],
 ['Summons,The'],
 ['Grisham,', 'John'],
 ['869,671'],
 ['Random', 'House'],
 ['83'],
 ['Small', 'Island'],
 ['Levy,', 'Andrea'],
 ['869,659'],
 ['Headline'],
 ['84'],
 ['Nigella', 'Express'],
 ['Lawson,', 'Nigella'],
 ['862,602'],
 ['Random', 'House'],
 ['85'],
 ['Brick', 'Lane'],
 ['Ali,', 'Monica'],
 ['856,540'],
 ['Transworld'],
 ['86'],
 ['Memory', "Keeper's", 'Daughter,The'],
 ['Edwards,', 'Kim'],
 ['845,858'],
 ['Penguin'],
 ['87'],
 ['Room', 'on', 'the', 'Broom'],
 ['Donaldson,', 'Julia'],
 ['842,535'],
 ['Pan', 'Macmillan'],
 ['88'],
 ['About', 'a', 'Boy'],
 ['Hornby,', 'Nick'],
 ['828,215'],
 ['Penguin'],
 ['89'],
 ['My', 'Booky', 'Wook'],
 ['Brand,', 'Russell'],
 ['820,563'],
 ['Hodder', '&', 'Stoughton'],
 ['90'],
 ['God', 'Delusion,The'],
 ['Dawkins,', 'Richard'],
 ['816,907'],
 ['Transworld'],
 ['91'],
 ['"Beano"', 'Annual,The'],
 ['0'],
 ['816,585'],
 ['D.C.', 'Thomson'],
 ['92'],
 ['White', 'Teeth'],
 ['Smith,', 'Zadie'],
 ['815,586'],
 ['Penguin'],
 ['93'],
 ['House', 'at', 'Riverton,The'],
 ['Morton,', 'Kate'],
 ['814,370'],
 ['Pan', 'Macmillan'],
 ['94'],
 ['Book', 'Thief,The'],
 ['Zusak,', 'Markus'],
 ['809,641'],
 ['Transworld'],
 ['95'],
 ['Nights', 'of', 'Rain', 'and', 'Stars'],
 ['Binchy,', 'Maeve'],
 ['808,900'],
 ['Orion'],
 ['96'],
 ['Ghost,The'],
 ['Harris,', 'Robert'],
 ['807,311'],
 ['Random', 'House'],
 ['97'],
 ['Happy', 'Days', 'with', 'the', 'Naked', 'Chef'],
 ['Oliver,', 'Jamie'],
 ['794,201'],
 ['Penguin'],
 ['98'],
 ['Hunger', 'Games,The:Hunger', 'Games', 'Trilogy'],
 ['Collins,', 'Suzanne'],
 ['792,187'],
 ['Scholastic', 'Ltd.'],
 ['99'],
 ['Lost',
  'Boy,The:A',
  'Foster',
  "Child's",
  'Search',
  'for',
  'the',
  'Love',
  'of',
  'a',
  'Family'],
 ['Pelzer,', 'Dave'],
 ['791,507'],
 ['Orion'],
 ['100'],
 ["Jamie's",
  'Ministry',
  'of',
  'Food:Anyone',
  'Can',
  'Learn',
  'to',
  'Cook',
  'in',
  '24',
  'Hours'],
 ['Oliver,', 'Jamie'],
 ['791,095'],
 ['Penguin'],
 '1',
 'Da',
 'Brown,',
 '5,094,805',
 'Transworld',
 '2',
 'Harry',
 'Rowling,',
 '4,475,152',
 'Bloomsbury',
 '3',
 'Harry',
 'Rowling,',
 '4,200,654',
 'Bloomsbury',
 '4',
 'Harry',
 'Rowling,',
 '4,179,479',
 'Bloomsbury',
 '5',
 'Fifty',
 'James,',
 '3,758,936',
 'Random',
 '6',
 'Harry',
 'Rowling,',
 '3,583,215',
 'Bloomsbury',
 '7',
 'Harry',
 'Rowling,',
 '3,484,047',
 'Bloomsbury',
 '8',
 'Harry',
 'Rowling,',
 '3,377,906',
 'Bloomsbury',
 '9',
 'Angels',
 'Brown,',
 '3,193,946',
 'Transworld',
 '10',
 'Harry',
 'Rowling,',
 '2,950,264',
 'Bloomsbury',
 '11',
 'Fifty',
 'James,',
 '2,479,784',
 'Random',
 '12',
 'Twilight',
 'Meyer,',
 '2,315,405',
 'Little,',
 '13',
 'Girl',
 'Larsson,',
 '2,233,570',
 'Quercus',
 '14',
 'Fifty',
 'James,',
 '2,193,928',
 'Random',
 '15',
 'Lost',
 'Brown,',
 '2,183,031',
 'Transworld',
 '16',
 'New',
 'Meyer,',
 '2,152,737',
 'Little,',
 '17',
 'Deception',
 'Brown,',
 '2,062,145',
 'Transworld',
 '18',
 'Eclipse',
 'Meyer,',
 '2,052,876',
 'Little,',
 '19',
 'Lovely',
 'Sebold,',
 '2,005,598',
 'Pan',
 '20',
 'Curious',
 'Haddon,',
 '1,979,552',
 'Random',
 '21',
 'Digital',
 'Brown,',
 '1,928,900',
 'Transworld',
 '22',
 'Short',
 'Bryson,',
 '1,852,919',
 'Transworld',
 '23',
 'Girl',
 'Larsson,',
 '1,814,784',
 'Quercus',
 '24',
 'Breaking',
 'Meyer,',
 '1,787,118',
 'Little,',
 '25',
 'Very',
 'Carle,',
 '1,783,535',
 'Penguin',
 '26',
 'Gruffalo,The',
 'Donaldson,',
 '1,781,269',
 'Pan',
 '27',
 "Jamie's",
 'Oliver,',
 '1,743,266',
 'Penguin',
 '28',
 'Kite',
 'Hosseini,',
 '1,629,119',
 'Bloomsbury',
 '29',
 'One',
 'Nicholls,',
 '1,616,068',
 'Hodder',
 '30',
 'Thousand',
 'Hosseini,',
 '1,583,992',
 'Bloomsbury',
 '31',
 'Girl',
 'Larsson,',
 '1,555,135',
 'Quercus',
 '32',
 'Time',
 'Niffenegger,',
 '1,546,886',
 'Random',
 '33',
 'Atonement',
 'McEwan,',
 '1,539,428',
 'Random',
 '34',
 'Bridget',
 'Fielding,',
 '1,508,205',
 'Pan',
 '35',
 'World',
 'Clarkson,',
 '1,489,403',
 'Penguin',
 '36',
 'Captain',
 'Bernieres,',
 '1,352,318',
 'Random',
 '37',
 'Sound',
 'Kay,',
 '1,310,207',
 'Random',
 '38',
 'Life',
 'Martel,',
 '1,310,176',
 'Canongate',
 '39',
 'Billy',
 'Stephenson,',
 '1,231,957',
 'HarperCollins',
 '40',
 'Child',
 'Pelzer,',
 '1,217,712',
 'Orion',
 '41',
 "Gruffalo's",
 'Donaldson,',
 '1,208,711',
 'Pan',
 '42',
 "Angela's",
 'McCourt,',
 '1,204,058',
 'HarperCollins',
 '43',
 'Birdsong',
 'Faulks,',
 '1,184,967',
 'Random',
 '44',
 'Northern',
 'Pullman,',
 '1,181,503',
 'Scholastic',
 '45',
 'Labyrinth',
 'Mosse,',
 '1,181,093',
 'Orion',
 '46',
 'Harry',
 'Rowling,',
 '1,153,181',
 'Bloomsbury',
 '47',
 'Help,The',
 'Stockett,',
 '1,132,336',
 'Penguin',
 '48',
 'Man',
 'Parsons,',
 '1,130,802',
 'HarperCollins',
 '49',
 'Memoirs',
 'Golden,',
 '1,126,337',
 'Random',
 '50',
 'No.1',
 'McCall',
 '1,115,549',
 'Little,',
 '51',
 'Island,The',
 'Hislop,',
 '1,108,328',
 'Headline',
 '52',
 'PS,',
 'Ahern,',
 '1,107,379',
 'HarperCollins',
 '53',
 'You',
 'McKeith,',
 '1,104,403',
 'Penguin',
 '54',
 'Shadow',
 'Zafon,',
 '1,092,349',
 'Orion',
 '55',
 'Tales',
 'Rowling,',
 '1,090,847',
 'Bloomsbury',
 '56',
 'Broker,The',
 'Grisham,',
 '1,087,262',
 'Random',
 '57',
 'Dr.',
 'Atkins,',
 '1,054,196',
 'Random',
 '58',
 'Subtle',
 'Pullman,',
 '1,037,160',
 'Scholastic',
 '59',
 'Eats,',
 'Truss,',
 '1,023,688',
 'Profile',
 '60',
 "Delia's",
 'Smith,',
 '1,015,956',
 'Random',
 '61',
 'Chocolat',
 'Harris,',
 '1,009,873',
 'Transworld',
 '62',
 'Boy',
 'Boyne,',
 '1,004,414',
 'Random',
 '63',
 'My',
 'Picoult,',
 '1,003,780',
 'Hodder',
 '64',
 'Amber',
 'Pullman,',
 '1,002,314',
 'Scholastic',
 '65',
 'To',
 'Lee,',
 '998,213',
 'Random',
 '66',
 'Men',
 'Gray,',
 '992,846',
 'HarperCollins',
 '67',
 'Dear',
 'French,',
 '986,753',
 'Random',
 '68',
 'Short',
 'Lewycka,',
 '986,115',
 'Penguin',
 '69',
 'Hannibal',
 'Harris,',
 '970,509',
 'Random',
 '70',
 'Lord',
 'Tolkien,',
 '967,466',
 'HarperCollins',
 '71',
 'Stupid',
 'Moore,',
 '963,353',
 'Penguin',
 '72',
 'Interpretation',
 'Rubenfeld,',
 '962,515',
 'Headline',
 '73',
 'Sharon',
 'Osbourne,',
 '959,496',
 'Little,',
 '74',
 'Alchemist,The:A',
 'Coelho,',
 '956,114',
 'HarperCollins',
 '75',
 'At',
 "O'Grady,",
 '945,640',
 'Transworld',
 '76',
 'Notes',
 'Bryson,',
 '931,312',
 'Transworld',
 '77',
 'Return',
 'Oliver,',
 '925,425',
 'Penguin',
 '78',
 'Bridget',
 'Fielding,',
 '924,695',
 'Pan',
 '79',
 "Jamie's",
 'Oliver,',
 '906,968',
 'Penguin',
 '80',
 'I',
 'McKenna,',
 '905,086',
 'Transworld',
 '81',
 'Down',
 'Bryson,',
 '890,847',
 'Transworld',
 '82',
 'Summons,The',
 'Grisham,',
 '869,671',
 'Random',
 '83',
 'Small',
 'Levy,',
 '869,659',
 'Headline',
 '84',
 'Nigella',
 'Lawson,',
 '862,602',
 'Random',
 '85',
 'Brick',
 'Ali,',
 '856,540',
 'Transworld',
 '86',
 'Memory',
 'Edwards,',
 '845,858',
 'Penguin',
 '87',
 'Room',
 'Donaldson,',
 '842,535',
 'Pan',
 '88',
 'About',
 'Hornby,',
 '828,215',
 'Penguin',
 '89',
 'My',
 'Brand,',
 '820,563',
 'Hodder',
 '90',
 'God',
 'Dawkins,',
 '816,907',
 'Transworld',
 '91',
 '"Beano"',
 '0',
 '816,585',
 'D.C.',
 '92',
 'White',
 'Smith,',
 '815,586',
 'Penguin',
 '93',
 'House',
 'Morton,',
 '814,370',
 'Pan',
 '94',
 'Book',
 'Zusak,',
 '809,641',
 'Transworld',
 '95',
 'Nights',
 'Binchy,',
 '808,900',
 'Orion',
 '96',
 'Ghost,The',
 'Harris,',
 '807,311',
 'Random',
 '97',
 'Happy',
 'Oliver,',
 '794,201',
 'Penguin',
 '98',
 'Hunger',
 'Collins,',
 '792,187',
 'Scholastic',
 '99',
 'Lost',
 'Pelzer,',
 '791,507',
 'Orion',
 '100',
 "Jamie's",
 'Oliver,',
 '791,095',
 'Penguin']

In [75]:
#7
driver = webdriver.Chrome(r'C:\New folder\webdriver.exe')
driver.get('http://www.imdb.com/list/ls095964455/')

In [185]:
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

In [186]:
tag1 = driver.find_elements(By.XPATH,'//h3[@class="lister-item-header"]')
for i in tag1:
    Name.append(i.text.split('.')[1].split('(')[0])
    
    
tag2 = driver.find_elements(By.XPATH,'//span[@class="lister-item-year text-muted unbold"]')
for i in tag2:
    Year_span.append(i.text)
    
tag3 = driver.find_elements(By.XPATH,'//span[@class="genre"]')
for i in tag3:
    Genre.append(i.text)
    
tag4 = driver.find_elements(By.XPATH,'//span[@class="runtime"]')
for i in tag4:
    Run_time.append(i.text)
    
tag5 = driver.find_elements(By.XPATH,'//div[@class="ipl-rating-star small"]')
for i in tag5:
    Ratings.append(i.text)
    
tag6 = driver.find_elements(By.XPATH,'//div[@class="lister-item-content"]')
for i in tag6:
    Votes.append(i.text.split('\n')[6].split(':')[1])

In [189]:
print(len(Name),len(Year_span),len(Genre),len(Run_time),len(Ratings),len(Votes))

100 100 100 100 100 100

In [190]:
df = pd.DataFrame({'Name':Name,'Year span':Year_span,'Genre':Genre,'Run time':Run_time,'Ratings':Ratings,'Votes':Votes})
df

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,123,265"
1,Stranger Things,(2016–2024),"Drama, Fantasy, Horror",51 min,8.7,"1,211,191"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"1,007,067"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"297,137"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"256,063"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"50,733"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"62,619"
97,Criminal Minds,(2005– ),"Crime, Drama, Mystery",42 min,8.1,"202,955"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"42,044"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"250,781"

In [2]:
#8
driver = webdriver.Chrome(r'C:\New folder\webdriver.exe')
driver.get('https://archive.ics.uci.edu/')

In [3]:
search1 = driver.find_element(By.XPATH,'/html/body/table[2]/tbody/tr/td/span/b/a')
search1.click()

In [4]:
Dataset_name = []
Data_type = []
Task = []
Attribute_type = []
No_of_instances = []
No_of_attribute = []
Year = []

In [5]:
tag1 = driver.find_elements(By.XPATH,'//p[@class="normal"]')
for i in tag1:
    Dataset_name.append(i.text)

In [6]:
Dataset_name

['Classification (466)\nRegression (151)\nClustering (121)\nOther (56)',
 'Categorical (38)\nNumerical (422)\nMixed (55)',
 'Multivariate (480)\nUnivariate (30)\nSequential (59)\nTime-Series (126)\nText (69)\nDomain-Theory (23)\nOther (21)',
 'Life Sciences (147)\nPhysical Sciences (57)\nCS / Engineering (234)\nSocial Sciences (41)\nBusiness (45)\nGame (12)\nOther (81)',
 'Less than 10 (166)\n10 to 100 (279)\nGreater than 100 (110)',
 'Less than 100 (38)\n100 to 1000 (210)\nGreater than 1000 (339)',
 'Matrix (439)\nNon-Matrix (183)',
 'Table View  List View',
 'Abalone',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '4177 ',
 '8 ',
 '1995 ',
 'Adult',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '48842 ',
 '14 ',
 '1996 ',
 'Annealing',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '798 ',
 '38 ',
 ' ',
 'Anonymous Microsoft Web Data',
 ' ',
 'Recommender-Systems ',
 'Categorical ',
 '37711 ',
 '294 ',
 '1998 ',
 'Arrhythmia',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '452 ',
 '279 ',
 '1998 ',
 'Artificial Characters',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '6000 ',
 '7 ',
 '1992 ',
 'Audiology (Original)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '226 ',
 ' ',
 '1987 ',
 'Audiology (Standardized)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '226 ',
 '69 ',
 '1992 ',
 'Auto MPG',
 'Multivariate ',
 'Regression ',
 'Categorical, Real ',
 '398 ',
 '8 ',
 '1993 ',
 'Automobile',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer, Real ',
 '205 ',
 '26 ',
 '1987 ',
 'Badges',
 'Univariate, Text ',
 'Classification ',
 ' ',
 '294 ',
 '1 ',
 '1994 ',
 'Balance Scale',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '625 ',
 '4 ',
 '1994 ',
 'Balloons',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '16 ',
 '4 ',
 ' ',
 'Breast Cancer',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '286 ',
 '9 ',
 '1988 ',
 'Breast Cancer Wisconsin (Original)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '699 ',
 '10 ',
 '1992 ',
 'Breast Cancer Wisconsin (Prognostic)',
 'Multivariate ',
 'Classification, Regression ',
 'Real ',
 '198 ',
 '34 ',
 '1995 ',
 'Breast Cancer Wisconsin (Diagnostic)',
 'Multivariate ',
 'Classification ',
 'Real ',
 '569 ',
 '32 ',
 '1995 ',
 'Pittsburgh Bridges',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '108 ',
 '13 ',
 '1990 ',
 'Car Evaluation',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '1728 ',
 '6 ',
 '1997 ',
 'Census Income',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '48842 ',
 '14 ',
 '1996 ',
 'Chess (King-Rook vs. King-Knight)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Categorical, Integer ',
 ' ',
 '22 ',
 '1988 ',
 'Chess (King-Rook vs. King-Pawn)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '3196 ',
 '36 ',
 '1989 ',
 'Chess (King-Rook vs. King)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '28056 ',
 '6 ',
 '1994 ',
 'Chess (Domain Theories)',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Bach Chorales',
 'Univariate, Time-Series ',
 ' ',
 'Categorical, Integer ',
 '100 ',
 '6 ',
 ' ',
 'Connect-4',
 'Multivariate, Spatial ',
 'Classification ',
 'Categorical ',
 '67557 ',
 '42 ',
 '1995 ',
 'Credit Approval',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '690 ',
 '15 ',
 ' ',
 'Japanese Credit Screening',
 'Multivariate, Domain-Theory ',
 'Classification ',
 'Categorical, Real, Integer ',
 '125 ',
 ' ',
 '1992 ',
 'Computer Hardware',
 'Multivariate ',
 'Regression ',
 'Integer ',
 '209 ',
 '9 ',
 '1987 ',
 'Contraceptive Method Choice',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '1473 ',
 '9 ',
 '1997 ',
 'Covertype',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '581012 ',
 '54 ',
 '1998 ',
 'Cylinder Bands',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '512 ',
 '39 ',
 '1995 ',
 'Dermatology',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '366 ',
 '33 ',
 '1998 ',
 'Diabetes',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Integer ',
 ' ',
 '20 ',
 ' ',
 'DGP2 - The Second Data Generation Program',
 'Data-Generator ',
 ' ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Document Understanding',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1994 ',
 'EBL Domain Theories',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Echocardiogram',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '132 ',
 '12 ',
 '1989 ',
 'Ecoli',
 'Multivariate ',
 'Classification ',
 'Real ',
 '336 ',
 '8 ',
 '1996 ',
 'Flags',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '194 ',
 '30 ',
 '1990 ',
 'Function Finding',
 ' ',
 'Function-Learning ',
 'Real ',
 '352 ',
 ' ',
 '1990 ',
 'Glass Identification',
 'Multivariate ',
 'Classification ',
 'Real ',
 '214 ',
 '10 ',
 '1987 ',
 "Haberman's Survival",
 'Multivariate ',
 'Classification ',
 'Integer ',
 '306 ',
 '3 ',
 '1999 ',
 'Hayes-Roth',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '160 ',
 '5 ',
 '1989 ',
 'Heart Disease',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '303 ',
 '75 ',
 '1988 ',
 'Hepatitis',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '155 ',
 '19 ',
 '1988 ',
 'Horse Colic',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '368 ',
 '27 ',
 '1989 ',
 'ICU',
 'Multivariate, Time-Series ',
 ' ',
 'Real ',
 ' ',
 ' ',
 ' ',
 'Image Segmentation',
 'Multivariate ',
 'Classification ',
 'Real ',
 '2310 ',
 '19 ',
 '1990 ',
 'Internet Advertisements',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '3279 ',
 '1558 ',
 '1998 ',
 'Ionosphere',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '351 ',
 '34 ',
 '1989 ',
 'Iris',
 'Multivariate ',
 'Classification ',
 'Real ',
 '150 ',
 '4 ',
 '1988 ',
 'ISOLET',
 'Multivariate ',
 'Classification ',
 'Real ',
 '7797 ',
 '617 ',
 '1994 ',
 'Kinship',
 'Relational ',
 'Relational-Learning ',
 'Categorical ',
 '104 ',
 '12 ',
 '1990 ',
 'Labor Relations',
 'Multivariate ',
 ' ',
 'Categorical, Integer, Real ',
 '57 ',
 '16 ',
 '1988 ',
 'LED Display Domain',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Categorical ',
 ' ',
 '7 ',
 '1988 ',
 'Lenses',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '24 ',
 '4 ',
 '1990 ',
 'Letter Recognition',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '20000 ',
 '16 ',
 '1991 ',
 'Liver Disorders',
 'Multivariate ',
 ' ',
 'Categorical, Integer, Real ',
 '345 ',
 '7 ',
 '1990 ',
 'Logic Theorist',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Lung Cancer',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '32 ',
 '56 ',
 '1992 ',
 'Lymphography',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '148 ',
 '18 ',
 '1988 ',
 'Mechanical Analysis',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '209 ',
 '8 ',
 '1990 ',
 'Meta-data',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '528 ',
 '22 ',
 '1996 ',
 'Mobile Robots',
 'Domain-Theory ',
 ' ',
 'Categorical, Integer, Real ',
 ' ',
 ' ',
 '1995 ',
 'Molecular Biology (Promoter Gene Sequences)',
 'Sequential, Domain-Theory ',
 'Classification ',
 'Categorical ',
 '106 ',
 '58 ',
 '1990 ',
 'Molecular Biology (Protein Secondary Structure)',
 'Sequential ',
 'Classification ',
 'Categorical ',
 '128 ',
 ' ',
 ' ',
 'Molecular Biology (Splice-junction Gene Sequences)',
 'Sequential, Domain-Theory ',
 'Classification ',
 'Categorical ',
 '3190 ',
 '61 ',
 '1992 ',
 "MONK's Problems",
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '432 ',
 '7 ',
 '1992 ',
 'Moral Reasoner',
 'Domain-Theory ',
 ' ',
 ' ',
 '202 ',
 ' ',
 '1994 ',
 'Multiple Features',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '2000 ',
 '649 ',
 ' ',
 'Mushroom',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '8124 ',
 '22 ',
 '1987 ',
 'Musk (Version 1)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '476 ',
 '168 ',
 '1994 ',
 'Musk (Version 2)',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '6598 ',
 '168 ',
 '1994 ',
 'Nursery',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '12960 ',
 '8 ',
 '1997 ',
 'Othello Domain Theory',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1991 ',
 'Page Blocks Classification',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '5473 ',
 '10 ',
 '1995 ',
 'Optical Recognition of Handwritten Digits',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '5620 ',
 '64 ',
 '1998 ',
 'Pen-Based Recognition of Handwritten Digits',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '10992 ',
 '16 ',
 '1998 ',
 'Post-Operative Patient',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '90 ',
 '8 ',
 '1993 ',
 'Primary Tumor',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '339 ',
 '17 ',
 '1988 ',
 'Prodigy',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Qualitative Structure Activity Relationships',
 'Domain-Theory ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Quadruped Mammals',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 ' ',
 '72 ',
 '1992 ',
 'Servo',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer ',
 '167 ',
 '4 ',
 '1993 ',
 'Shuttle Landing Control',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '15 ',
 '6 ',
 '1988 ',
 'Solar Flare',
 'Multivariate ',
 'Regression ',
 'Categorical ',
 '1389 ',
 '10 ',
 '1989 ',
 'Soybean (Large)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '307 ',
 '35 ',
 '1988 ',
 'Soybean (Small)',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '47 ',
 '35 ',
 '1987 ',
 'Challenger USA Space Shuttle O-Ring',
 'Multivariate ',
 'Regression ',
 'Integer ',
 '23 ',
 '4 ',
 '1993 ',
 'Low Resolution Spectrometer',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '531 ',
 '102 ',
 '1988 ',
 'Spambase',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '4601 ',
 '57 ',
 '1999 ',
 'SPECT Heart',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '267 ',
 '22 ',
 '2001 ',
 'SPECTF Heart',
 'Multivariate ',
 'Classification ',
 'Integer ',
 '267 ',
 '44 ',
 '2001 ',
 'Sponge',
 'Multivariate ',
 'Clustering ',
 'Categorical, Integer ',
 '76 ',
 '45 ',
 ' ',
 'Statlog Project',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 '1992 ',
 'Student Loan Relational',
 'Domain-Theory ',
 ' ',
 ' ',
 '1000 ',
 ' ',
 '1993 ',
 'Teaching Assistant Evaluation',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '151 ',
 '5 ',
 '1997 ',
 'Tic-Tac-Toe Endgame',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '958 ',
 '9 ',
 '1991 ',
 'Thyroid Disease',
 'Multivariate, Domain-Theory ',
 'Classification ',
 'Categorical, Real ',
 '7200 ',
 '21 ',
 '1987 ',
 'Trains',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '10 ',
 '32 ',
 '1994 ',
 'University',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '285 ',
 '17 ',
 '1988 ',
 'Congressional Voting Records',
 'Multivariate ',
 'Classification ',
 'Categorical ',
 '435 ',
 '16 ',
 '1987 ',
 'Water Treatment Plant',
 'Multivariate ',
 'Clustering ',
 'Integer, Real ',
 '527 ',
 '38 ',
 '1993 ',
 'Waveform Database Generator (Version 1)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 '5000 ',
 '21 ',
 '1988 ',
 'Waveform Database Generator (Version 2)',
 'Multivariate, Data-Generator ',
 'Classification ',
 'Real ',
 '5000 ',
 '40 ',
 '1988 ',
 'Wine',
 'Multivariate ',
 'Classification ',
 'Integer, Real ',
 '178 ',
 '13 ',
 '1991 ',
 'Yeast',
 'Multivariate ',
 'Classification ',
 'Real ',
 '1484 ',
 '8 ',
 '1996 ',
 'Zoo',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '101 ',
 '17 ',
 '1990 ',
 'Undocumented',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Twenty Newsgroups',
 'Text ',
 ' ',
 ' ',
 '20000 ',
 ' ',
 '1999 ',
 'Australian Sign Language signs',
 'Multivariate, Time-Series ',
 'Classification ',
 'Categorical, Real ',
 '6650 ',
 '15 ',
 '1999 ',
 'Australian Sign Language signs (High Quality)',
 'Multivariate, Time-Series ',
 'Classification ',
 'Real ',
 '2565 ',
 '22 ',
 '2002 ',
 'US Census Data (1990)',
 'Multivariate ',
 'Clustering ',
 'Categorical ',
 '2458285 ',
 '68 ',
 ' ',
 'Census-Income (KDD)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '299285 ',
 '40 ',
 '2000 ',
 'Coil 1999 Competition Data',
 'Multivariate ',
 ' ',
 'Categorical, Real ',
 '340 ',
 '17 ',
 '1999 ',
 'Corel Image Features',
 'Multivariate ',
 ' ',
 'Real ',
 '68040 ',
 '89 ',
 '1999 ',
 'E. Coli Genes',
 'Relational ',
 ' ',
 ' ',
 ' ',
 ' ',
 '2001 ',
 'EEG Database',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Integer, Real ',
 '122 ',
 '4 ',
 '1999 ',
 'El Nino',
 'Spatio-temporal ',
 ' ',
 'Integer, Real ',
 '178080 ',
 '12 ',
 '1999 ',
 'Entree Chicago Recommendation Data',
 'Transactional, Sequential ',
 'Recommender-Systems ',
 'Categorical ',
 '50672 ',
 ' ',
 '2000 ',
 'CMU Face Images',
 'Image ',
 'Classification ',
 'Integer ',
 '640 ',
 ' ',
 '1999 ',
 'Insurance Company Benchmark (COIL 2000)',
 'Multivariate ',
 'Regression, Description ',
 'Categorical, Integer ',
 '9000 ',
 '86 ',
 '2000 ',
 'Internet Usage Data',
 'Multivariate ',
 ' ',
 'Categorical, Integer ',
 '10104 ',
 '72 ',
 '1999 ',
 'IPUMS Census Database',
 'Multivariate ',
 ' ',
 'Categorical, Integer ',
 '256932 ',
 '61 ',
 '1999 ',
 'Japanese Vowels',
 'Multivariate, Time-Series ',
 'Classification ',
 'Real ',
 '640 ',
 '12 ',
 ' ',
 'KDD Cup 1998 Data',
 'Multivariate ',
 'Regression ',
 'Categorical, Integer ',
 '191779 ',
 '481 ',
 '1998 ',
 'KDD Cup 1999 Data',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '4000000 ',
 '42 ',
 '1999 ',
 'M. Tuberculosis Genes',
 'Relational ',
 ' ',
 ' ',
 ' ',
 ' ',
 '2001 ',
 'Movie',
 'Multivariate, Relational ',
 ' ',
 ' ',
 '10000 ',
 ' ',
 '1999 ',
 'MSNBC.com Anonymous Web Data',
 'Sequential ',
 ' ',
 'Categorical ',
 '989818 ',
 ' ',
 ' ',
 'NSF Research Award Abstracts 1990-2003',
 'Text ',
 ' ',
 ' ',
 '129000 ',
 ' ',
 '2003 ',
 'Pioneer-1 Mobile Robot Data',
 'Multivariate, Time-Series ',
 ' ',
 'Categorical, Real ',
 ' ',
 ' ',
 '1999 ',
 'Pseudo Periodic Synthetic Time Series',
 'Univariate, Time-Series ',
 ' ',
 ' ',
 '100000 ',
 ' ',
 '1999 ',
 'Reuters-21578 Text Categorization Collection',
 'Text ',
 'Classification ',
 'Categorical ',
 '21578 ',
 '5 ',
 '1997 ',
 'Robot Execution Failures',
 'Multivariate, Time-Series ',
 'Classification ',
 'Integer ',
 '463 ',
 '90 ',
 '1999 ',
 'Synthetic Control Chart Time Series',
 'Time-Series ',
 'Classification, Clustering ',
 'Real ',
 '600 ',
 ' ',
 '1999 ',
 'Syskill and Webert Web Page Ratings',
 'Multivariate, Text ',
 'Classification ',
 'Categorical ',
 '332 ',
 '5 ',
 '1998 ',
 'UNIX User Data',
 'Text, Sequential ',
 ' ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Volcanoes on Venus - JARtool experiment',
 'Image ',
 'Classification ',
 ' ',
 ' ',
 ' ',
 ' ',
 'Statlog (Australian Credit Approval)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer, Real ',
 '690 ',
 '14 ',
 ' ',
 'Statlog (German Credit Data)',
 'Multivariate ',
 'Classification ',
 'Categorical, Integer ',
 '1000 ',
 ...]